import java.util.Scanner;

//@author NAYAK
public class Binary_Search {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter an array to iniate Binary Search");
        System.out.println("Enter the length of array:");
        int length = sc.nextInt();
        int arr[] = new int[length];
        for (int i=0; i<length; i++) {
            System.out.println("Enter element " +i+ ":-");
            arr[i] = sc.nextInt();
        }
        System.out.println("Enter the number to find index of:");
        int ind = sc.nextInt();
        System.out.println(ind+" is present at " + binarysearch(arr, ind));



        sc.close();
    }
    public static int binarysearch(int[] a, int b){
        // The below line of code was auto generated by intelliJ , however it is not wrong...
        //return IntStream.range(0, a.length).filter(i -> a[i] == b).findFirst().orElse(-1);
        for (int i=0; i<a.length; i++) {
          if(a[i] == b) return i;
        }
        return -1;
    }

}
